---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: testuser # namespace к которому применяются огранияения
  name: testuser
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
 name: testuser-rb
 namespace: testuser
subjects: 
- kind: User
  name: testuser
  apiGroup: rbac.authorization.k8s.io 
roleRef:
 kind: Role
 name: testuser
 apiGroup: rbac.authorization.k8s.io
